// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-weddings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_weddings_default = defineTool({
  name: "list_weddings",
  title: "Elenca matrimoni",
  description: "Elenca i matrimoni a cui l'utente autenticato ha accesso (via user_roles), con data e sposi.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data: roles, error: rolesError } = await sb.from("user_roles").select("wedding_id, role").eq("user_id", ctx.getUserId());
    if (rolesError)
      return { content: [{ type: "text", text: rolesError.message }], isError: true };
    const ids = Array.from(new Set((roles ?? []).map((r) => r.wedding_id).filter(Boolean)));
    if (ids.length === 0)
      return {
        content: [{ type: "text", text: "Nessun matrimonio trovato." }],
        structuredContent: { weddings: [] }
      };
    const { data: weddings, error } = await sb.from("weddings").select("id, partner1_name, partner2_name, wedding_date, venue_name").in("id", ids);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (weddings ?? []).map((w) => ({
      ...w,
      role: roles?.find((r) => r.wedding_id === w.id)?.role
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { weddings: rows }
    };
  }
});

// src/lib/mcp/tools/list-guests.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_guests_default = defineTool2({
  name: "list_guests",
  title: "Elenca ospiti",
  description: "Elenca gli ospiti di un matrimonio con nome, RSVP e nucleo. Filtra opzionalmente per stato RSVP.",
  inputSchema: {
    wedding_id: z.string().uuid().describe("ID del matrimonio"),
    rsvp_status: z.enum(["pending", "confirmed", "declined", "maybe"]).optional().describe("Filtra per stato RSVP"),
    limit: z.number().int().min(1).max(500).default(200)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ wedding_id, rsvp_status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    const sb = supabaseForUser2(ctx);
    let q = sb.from("guests").select("id, first_name, last_name, party_name, rsvp_status, is_child, is_staff, email, phone").eq("wedding_id", wedding_id).limit(limit);
    if (rsvp_status) q = q.eq("rsvp_status", rsvp_status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} ospiti
${JSON.stringify(data, null, 2)}` }],
      structuredContent: { guests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_vendors_default = defineTool3({
  name: "list_vendors",
  title: "Elenca fornitori",
  description: "Elenca i fornitori di un matrimonio con nome, categoria e stato.",
  inputSchema: {
    wedding_id: z2.string().uuid().describe("ID del matrimonio")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ wedding_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("vendors").select("id, name, status, email, phone, expense_categories(name)").eq("wedding_id", wedding_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        { type: "text", text: `${data?.length ?? 0} fornitori
${JSON.stringify(data, null, 2)}` }
      ],
      structuredContent: { vendors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/budget-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var budget_summary_default = defineTool4({
  name: "budget_summary",
  title: "Riepilogo budget",
  description: "Restituisce il budget totale, la somma delle spese pianificate e la somma dei pagamenti registrati.",
  inputSchema: { wedding_id: z3.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ wedding_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const [w, exp, pay] = await Promise.all([
      sb.from("weddings").select("total_budget, partner1_name, partner2_name, wedding_date").eq("id", wedding_id).maybeSingle(),
      sb.from("expense_items").select("id, name, amount, estimated_cost, actual_cost").eq("wedding_id", wedding_id),
      sb.from("payments").select("amount, is_paid, expense_item_id").eq("wedding_id", wedding_id)
    ]);
    if (w.error) return { content: [{ type: "text", text: w.error.message }], isError: true };
    const expenses = exp.data ?? [];
    const payments = pay.data ?? [];
    const totalExpenses = expenses.reduce(
      (s, e) => s + Number(e.amount ?? e.actual_cost ?? e.estimated_cost ?? 0),
      0
    );
    const totalPaid = payments.filter((p) => p.is_paid).reduce((s, p) => s + Number(p.amount ?? 0), 0);
    const totalPlanned = payments.reduce((s, p) => s + Number(p.amount ?? 0), 0);
    const summary = {
      wedding: w.data,
      total_budget: Number(w.data?.total_budget ?? 0),
      total_expenses: totalExpenses,
      total_planned_payments: totalPlanned,
      total_paid: totalPaid,
      remaining_to_pay: totalPlanned - totalPaid,
      expense_count: expenses.length,
      payment_count: payments.length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "evaivaudtestjzckutsd";
var mcp_default = defineMcp({
  name: "wedsapp-mcp",
  title: "WedsApp",
  version: "0.1.0",
  instructions: "Strumenti per WedsApp \u2014 gestionale matrimoni. Usa list_weddings per trovare l'ID del matrimonio, poi list_guests, list_vendors o budget_summary per interrogare i dati.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_weddings_default, list_guests_default, list_vendors_default, budget_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
